### ISSUE TITLE
setup.py needs modernising

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/panedr#26]
Sorry mostly a brain dump but it's all tiny stuff that probably needs doing.

Python requires don't match any current versions of Python.

Also the setup.cfg is geared towards creating universal wheels, but I would proposed dropping py2.7 and go 3.8+ (i.e. drop universal wheels).

There's a few other things that probably need to be done in setup.py but I haven't had a deep look.

**Comment by IAlibay** [comment]
This actually needs to get done first @BFedder otherwise you can't pip install from source I _think_.

**Comment by BFedder** [comment]
Is anything left to do here now that installing from source works?

**Comment by IAlibay** [comment]
Should all be done now, we can deal with pyproject.toml at a later point.
