### ISSUE TITLE
Add coverage

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/panedr#29]
Adding a codecov action would be nice for keeping track of where things are at tests wise.

**Comment by BFedder** [comment]
So there is a codecov action defined in the .yaml file #32 will add, but I am not sure if this will work out of the box or need further adaptation from GridDataFormats to panedr

**Comment by orbeckst** [comment]
82% coverage is not too shabby to start with...

**Comment by orbeckst** [comment]
But it's worthwhile taking a look at https://app.codecov.io/gh/MDAnalysis/panedr/blob/master/panedr/panedr.py and seeing if there's something that really ought to be tested. One can always raise specific issues for certain tests.
