### ISSUE TITLE
Add numpy to requirements.txt

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/panedr#39]
As discussed on #33, we can make NumPy a required dependency.
Probably best to use the same version as MDA.

**Comment by hmacdope** [comment]
I can't assign you for some reason @BFedder.

**Comment by BFedder** [comment]
I had added NumPy as required dependency as part of #33, and have now changed it to require the same version(s) as MDAnalysis

**Comment by BFedder** [comment]
This is now merged. However, with MDAnalysis moving to numpy>1.20, it might be worth to do the same here, but this would mean dropping Python3.6. Do we want to do that here?

**Comment by IAlibay** [comment]
Imho no - MDA will enforce it's own subselection of numpy & python because it lives downstream. It's fine for panedr to support a wider range until it becomes absolutely necessary to restrict to a newer version.

**Comment by BFedder** [comment]
@hmacdope, are you happy for this issue to be closed now that numpy>1.19 is in requirements.txt?

**Comment by hmacdope** [comment]
Yep all good!
