### ISSUE TITLE
xdrlib is deprecated as of py3.11

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/panedr#49]
See https://peps.python.org/pep-0594/#xdrlib will be removed in py3.13

**Comment by orbeckst** [comment]
Are we just going to vendor it?

With GROMACS we will need xdrlib for eternity.

**Comment by IAlibay** [comment]
Makes sense to do so, code isn't too complicated: https://github.com/python/cpython/blob/3.10/Lib/xdrlib.py

But we'd have to make sure it's all good license wise (should be).

**Comment by orbeckst** [comment]
Is mda-xdrlib available now or is it waiting for https://github.com/MDAnalysis/mda-xdrlib/issues/2 ?

**Comment by IAlibay** [comment]
@orbeckst sorry that's waiting on a standalone action I'm trying to put together that will hopefully just deal with CD for everything (I'm currently trying to work out how to be a little bit more flexible so it can cover all the packages under the MDA umbrella that require pure python builds).
