### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/panedr#53]
Datafiles aren't included in the current pyedr pypi release, so we need to make a 0.6.1 🤦🏽 
EDIT (@orbeckst ): we have new features (PR #56 ) so this needs to be 0.7.0 instead of 0.6.1

Note: if I just copy the files over to the correct site-package location everything passes, so at least there's that.

**Comment by IAlibay** [comment]
Might need to move this to a 0.7.0 release.

**Comment by BFedder** [comment]
The EDRReader will need the recent changes to make unit handling work. What is left to be done before the next release @hmacdope @jbarnoud @IAlibay @orbeckst @fiona-naughton? 

Once any remaining issues are addressed, could I please ask you @IAlibay to take care of the next release (or show me how to do it myself)?

**Comment by orbeckst** [comment]
The new release needs to be a 0.7.0 because we added new features.

**Comment by orbeckst** [comment]
sure, let's move things along 🚀
