### ISSUE TITLE
Release 0.7.1 and conda-forge package

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/panedr#58]
Once #55 gets merged, I propose we release a 0.7.1 version (with the fixed packaging, i.e. #54 )

Then I'll create the pyedr conda-forge package and we can move ahead with a proper release.

**Comment by orbeckst** [comment]
We'll want the cf packages for the MDA 2.4.0 release https://github.com/MDAnalysis/mdanalysis/issues/3902 with the new EDRReader.

**Comment by IAlibay** [comment]
I'll block this to wait on #61 just in case further changes are needed.
