### ISSUE TITLE
remove test files from coverage

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/panedr#60]
At the moment, coverage includes the tests in the calculation. That's not particularly helpful and should be changed so that coverage excludes test files.

**Comment by IAlibay** [comment]
So a couple of months back one of the OpenFE folks actually convinced me that having coverage for test files is actually a good idea. The main idea being that it tells you when you have stuff in your tests that aren't actually doing anything (like leftover classes or code bits that just aren't getting executed for some reason).

**Comment by IAlibay** [comment]
I want to say @dwhswenson was the person who convinced me?

**Comment by dwhswenson** [comment]
Yep, that was me. And I was converted by the main developer of `coverage`. I think he makes the case clearly and concisely: https://nedbatchelder.com/blog/202008/you_should_include_your_tests_in_coverage.html

**Comment by orbeckst** [comment]
I have admittedly been looking at the test code as a second class citizen. After reading Ned's post I could become convinced that including the tests in coverage could be useful.

**Comment by orbeckst** [comment]
closing with "wont fix"
