### ISSUE TITLE
Blocking re-review for #55 

### ISSUE THREAD

**Issue by hmacdope** [MDAnalysis/panedr#61]
Apologies I prematurely merged #55 before getting feedback from @jbarnoud. 

This issue is to check that everything is all good for #55 post-hoc, with special focus on @IAlibay's query:

        Couple of small things - could use a second opinion on removing timing @orbeckst @jbarnoud @hmacdope

_Originally posted by @IAlibay in https://github.com/MDAnalysis/panedr/pull/55#pullrequestreview-1169218474_

and 

        lgtm - assuming @jbarnoud is fine with the changes here

_Originally posted by @IAlibay in https://github.com/MDAnalysis/panedr/pull/55#pullrequestreview-1169627598_

**Comment by jbarnoud** [comment]
I liked the adaptative progress bar. But tqdm is likely better 👍

**Comment by IAlibay** [comment]
thanks @jbarnoud
